# https://taskfile.dev

version: '3'

tasks:
  extract-i18n:
    cmds:
    - npm run ng extract-i18n -- --output-path src/locales

  build-docker:
    cmds:
    - npm run build-localize
    - docker build -t temp .
