# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to Google Play internal track"
  lane :internal do
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track: "internal-testing"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Promote Internal Testing to Closed Testing"
  lane :promote_internal_to_closed do
    upload_to_play_store(
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      track: "internal-testing",
      track_promote_to: "closed-testing",
    )
  end

  desc "Promote Closed Testing to Open Testing"
  lane :promote_closed_to_open do
    upload_to_play_store(
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      track: "closed-testing",
      track_promote_to: "open-testing",
    )
  end

  desc "Promote Open Testing to production"
  lane :promote_open_to_prod do
    upload_to_play_store(
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      track: "open-testing",
      track_promote_to: "production",
    )
  end
end
