platform: linux
image_resource:
  type: registry-image
  source: {repository: arduinoci/ci-arduino-esp32, tag: v2.0.16}
inputs:
- name: firmware-source
- name: firmware-version
outputs:
- name: artifact
caches:
- path: cache/arduino-cli
- path: cache/apt
run:
  path: bash
  args:
  - -ec
  - |
    FIRMWARE_VERSION=$(cat firmware-version/version)
    OUTPUT=$PWD/artifact
    CACHE_ARDUINOCLI=$PWD/cache/arduino-cli
    
    rm -rf /var/cache/apt /etc/apt/apt.conf.d/docker-clean
    ln -s $PWD/cache/apt /var/cache/apt
    
    apt-get update -qq
    apt-get install -y -qq pigz
    
    cd firmware-source/battery_alarm_firmware_mobile
    
    while read lib
    do
      arduino-cli lib install "$lib"
    done < .libraries
    
    cat > version.h <<EOT
    #pragma once
    
    #define VERSION "${FIRMWARE_VERSION}"
    EOT
    
    arduino-cli compile \
      battery_alarm_firmware_mobile.ino \
      --fqbn "$(cat .fqbn)" \
      --output-dir "$OUTPUT" \
      --build-path "$CACHE_ARDUINOCLI"/build \
      --build-cache-path "$CACHE_ARDUINOCLI"/build-cache
    
    cat "${OUTPUT}/battery_alarm_firmware_mobile.ino.bin" \
    | pigz -cz11 \
    > "${OUTPUT}/battery_alarm_firmware_mobile.ino.bin.z"
    
    ls -l "${OUTPUT}/battery_alarm_firmware_mobile.ino.bin"*
