temp:
  misc:
    alpine_image: &alpine_image
      type: registry-image
      source:
        repository: alpine
        tag: latest

  resources:
    repo: &repo
      type: git
      icon: github
      webhook_token: ((webhook_token))
      check_every: 24h
    repo_source: &repo_source
      uri: ((git.url))
      branch: ((git.branch))
      private_key: ((git.private_key))

    image: &image
      type: registry-image
      icon: floppy
    image_source: &image_source
      username: ((private-docker.username))
      password: ((private-docker.password))

    semver: &semver
      type: semver
      icon: numeric
    semver_source: &semver_source
      access_key_id: ((s3.access_key_id))
      bucket: ((s3.versions_bucket))
      driver: s3
      endpoint: ((s3.endpoint))
      region_name: ((s3.region_name))
      secret_access_key: ((s3.secret_access_key))
      initial_version: 0.0.1

    pub_artifact: &pub_artifact
      type: s3
      icon: floppy
    pub_artifact_source: &pub_artifact_source
      access_key_id: ((pub_s3.access_key_id))
      bucket: ((pub_s3.pub_bucket))
      region_name: ((pub_s3.region_name))
      secret_access_key: ((pub_s3.secret_access_key))

  tasks:
    slack_alert: &slack_alert
      on_failure:
        put: slack-alert
        params: { alert_type: failed }
      on_abort:
        put: slack-alert
        params: { alert_type: aborted }
      on_error:
        put: slack-alert
        params: { alert_type: errored }

    oci_task: &oci_task
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
        inputs:
        - name: docker
          path: .
        outputs:
        - name: image
        run:
          path: build

resources:
- name: pipeline-source
  <<: *repo
  source:
    <<: *repo_source
    paths:
    - ci/pipeline.yml

- name: ci
  <<: *repo
  source:
    <<: *repo_source
    paths:
    - ci
    - battery_alarm_app/android/fastlane
    - battery_alarm_app/android/Gemfile
    - battery_alarm_app/android/Gemfile.lock
    ignore_paths:
    - ci/pipeline.yml

# region docs

- name: docs-source
  <<: *repo
  source:
    <<: *repo_source
    paths:
    - docs/user_manual

- name: docs-image
  type: docker-manifest
  icon: floppy
  source:
    <<: *image_source
    repository: ((docs-image-repo))

- name: docs-image-arm64
  <<: *image
  source:
    <<: *image_source
    repository: ((docs-image-repo))
    tag: arm64

- name: docs-image-amd64
  <<: *image
  source:
    <<: *image_source
    repository: ((docs-image-repo))
    tag: amd64

- name: docs-image-version
  <<: *semver
  source:
    <<: *semver_source
    key: battalarm/docs-image-version

# endregion

# region chart

- name: chart-source
  <<: *repo
  source:
    <<: *repo_source
    paths:
    - helm

- name: chart-version
  <<: *semver
  source:
    <<: *semver_source
    key: battalarm/chart-version

- name: chart
  type: chartmuseum
  icon: map
  source:
    server_url: ((charts-repo.url))/api/charts
    chart_name: battalarm
    basic_auth_username: ((charts-repo.username))
    basic_auth_password: ((charts-repo.password))

# endregion

# region backend

- name: production
  type: helm
  check_every: 24h
  icon: factory
  source:
    admin_cert: ((helm.admin_cert))
    admin_key: ((helm.admin_key))
    cluster_ca_base64: ((helm.cluster_ca))
    cluster_url: ((helm.cluster_url))
    namespace: ((helm.namespace))
    release: ((helm.release))
    repos:
    - name: ((charts-repo.name))
      url: ((charts-repo.url))

# endregion

# region app

- name: app-source
  <<: *repo
  source:
    <<: *repo_source
    paths:
    - battery_alarm_app
    ignore_paths:
    - battery_alarm_app/android/fastlane
    - battery_alarm_app/android/Gemfile
    - battery_alarm_app/android/Gemfile.lock

- name: app-version
  <<: *semver
  source:
    <<: *semver_source
    key: battalarm/app/apk

- name: app-number-version
  <<: *semver
  source:
    <<: *semver_source
    key: battalarm/app/apk-number

# endregion

# region firmware

- name: firmware-source
  <<: *repo
  source:
    <<: *repo_source
    paths:
    - battery_alarm_firmware_mobile

- name: firmware-version
  <<: *semver
  source:
    <<: *semver_source
    key: battalarm/firmware

- name: firmware-beta-artifact
  <<: *pub_artifact
  source:
    <<: *pub_artifact_source
    initial_version: 0.0.0
    versioned_file: battalarm/firmware-beta.bin

- name: firmware-beta-artifact-version
  <<: *pub_artifact
  source:
    <<: *pub_artifact_source
    initial_version: 0.0.0
    versioned_file: battalarm/firmware-beta-version.txt

- name: firmware-artifact
  <<: *pub_artifact
  source:
    <<: *pub_artifact_source
    initial_version: 0.0.0
    versioned_file: battalarm/firmware.bin

- name: firmware-artifact-version
  <<: *pub_artifact
  source:
    <<: *pub_artifact_source
    initial_version: 0.0.0
    versioned_file: battalarm/firmware-version.txt

# endregion

- name: slack-alert
  type: slack
  icon: bell
  source:
    url: ((slack.webhook_url))
    channel: ((slack.sad))

resource_types:
- name: docker-manifest
  type: registry-image
  source:
    #repository: mbialon/concourse-docker-manifest-resource
    repository: timotto/concourse-docker-manifest-resource
    tag: private-registry

- name: chartmuseum
  type: registry-image
  source:
    repository: cathive/concourse-chartmuseum-resource

- name: helm
  type: registry-image
  source:
    repository: ghcr.io/typositoire/concourse-helm3-resource
    tag: v1.26.1

- name: slack
  type: registry-image
  source:
    repository: arbourd/concourse-slack-alert-resource

jobs:

# region pipeline

- name: pipeline
  serial: true
  plan:
  - <<: *slack_alert
    do:
    - get: pipeline-source
      trigger: true
    - set_pipeline: self
      file: pipeline-source/ci/pipeline.yml
      vars:
        docs-image-repo: ((docs-image-repo))

# endregion

# region docs

- name: docs
  serial: true
  serial_groups: [docs]
  plan:
  - <<: *slack_alert
    do:
    - in_parallel:
      - get: source-code
        resource: docs-source
        trigger: true
      - get: version
        resource: docs-image-version
        params: {bump: patch}
    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: node
            semver_constraint: "~20.x"
        inputs:
        - name: source-code
        outputs:
        - name: artifact
          path: source-code/docs/user_manual/dist/battery_alarm_user_manual
        caches:
        - path: source-code/docs/user_manual/node_modules
        run:
          path: bash
          dir: source-code/docs/user_manual
          args:
          - -exc
          - |
            npm i --no-progress < /dev/null
            npm run build < /dev/null
            cp -v nginx.conf Dockerfile dist/battery_alarm_user_manual

    - in_parallel:
      - do:
        - task: docs-image-arm64
          <<: *oci_task
          input_mapping:
            docker: artifact
          output_mapping:
            image: docs-image-arm64
          params:
            IMAGE_PLATFORM: linux/arm64
        - put: docs-image-arm64
          params:
            image: docs-image-arm64/image.tar
      - do:
        - task: docs-image-amd64
          <<: *oci_task
          input_mapping:
            docker: artifact
          output_mapping:
            image: docs-image-amd64
          params:
            IMAGE_PLATFORM: linux/amd64
        - put: docs-image-amd64
          params:
            image: docs-image-amd64/image.tar

    - in_parallel:
      - put: docs-image-version
        params: {file: version/version}
      - put: docs-image
        params:
          tag_file: version/version
          manifests:
          - arch: arm64
            variant: v8
            os: linux
            digest_file: docs-image-arm64/digest
          - arch: amd64
            os: linux
            digest_file: docs-image-amd64/digest

# endregion

# region chart

- name: chart
  serial: true
  serial_groups: [chart]
  plan:
  - <<: *slack_alert
    do:
    - in_parallel:
      - get: source-code
        resource: chart-source
        trigger: true
      - get: chart-version
        params: {bump: patch}

    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: ghcr.io/typositoire/concourse-helm3-resource
            tag: v1.26.1
        inputs:
        - name: source-code
        - name: chart-version
        outputs:
        - name: chart
        run:
          path: sh
          args:
          - -ec
          - |
            CHART_VERSION=$(cat chart-version/version)
            mkdir -p build
            helm package --destination build --version "$CHART_VERSION" source-code/helm/battalarm
            cp -v build/battalarm-*.tgz chart/battalarm.tgz

    - in_parallel:
      - put: chart-version
        params: {file: chart-version/version}
      - put: chart
        params:
          chart: chart/battalarm.tgz
          version_file: chart-version/version

# endregion

# region backend

- name: deploy
  serial: true
  serial_groups: [docs, chart]
  plan:
  - <<: *slack_alert
    do:
    - in_parallel:
      - get: docs-image-version
        trigger: true
        passed: [docs]
      - get: chart-version
        trigger: true
        passed: [chart]

    - task: values_yaml
      config:
        platform: linux
        image_resource:
          <<: *alpine_image
        outputs:
        - name: values
          path: .
        params:
          VALUES_YAML: ((prod.values_yaml))
        run:
          path: sh
          args:
          - -ec
          - |
            echo "$VALUES_YAML" > values.yaml

    - put: production
      params:
        chart: tims-charts/battalarm
        version: chart-version/version
        wait_until_ready: 300
        values: values/values.yaml
        override_values:
        - key: docs_image.tag
          path: docs-image-version/version
          type: string

# endregion

# region app

- name: app
  serial_groups: [app-version]
  plan:
  - in_parallel:
    - get: app-source
      trigger: true
    - put: app-version
      params:
        pre: build
    - put: app-number-version
      params:
        bump: major
    - get: ci

  - task: build
    file: ci/ci/tasks/build_app.yml
    params:
      RELEASE_KEYSTORE: ((android.release_keystore))
      RELEASE_KEYSTORE_PASSWORD: ((android.release_keystore_password))
      RELEASE_KEYSTORE_KEY_ALIAS: ((android.release_keystore_key_alias))
      RELEASE_KEYSTORE_KEY_PASSWORD: ((android.release_keystore_key_password))

  - in_parallel:
    - task: publish
      file: ci/ci/tasks/publish_android.yml
      params:
        FASTLANE_TARGET: internal
        SERVICE_ACCOUNT_JSON: ((android.service_account_json))

    - put: app-source
      params:
        repository: app-source
        tag: app-version/version
        tag_prefix: app-v
        only_tag: true

- name: promote-android-internal-to-open
  serial: true
  plan:
  - in_parallel:
    - get: app-version
      passed: [app]
    - get: ci

  - task: publish
    file: ci/ci/tasks/bump_android.yml
    params:
      FASTLANE_TARGET: promote_internal_to_open
      SERVICE_ACCOUNT_JSON: ((android.service_account_json))

- name: promote-android-open-to-prod
  serial: true
  plan:
  - in_parallel:
    - get: app-version
      passed: [promote-android-internal-to-open]
    - get: ci

  - task: publish
    file: ci/ci/tasks/bump_android.yml
    params:
      FASTLANE_TARGET: promote_open_to_prod
      SERVICE_ACCOUNT_JSON: ((android.service_account_json))

- name: bump-app-version-patch
  serial_groups: [app-version]
  serial: true
  plan:
  - in_parallel:
    - get: app-version
      passed: [promote-android-open-to-prod]
      trigger: true
    - put: app-version
      params:
        bump: patch

- name: bump-app-version-minor
  serial_groups: [app-version]
  serial: true
  plan:
  - in_parallel:
    - put: app-version
      params:
        bump: minor

- name: bump-app-version-major
  serial_groups: [app-version]
  serial: true
  plan:
  - in_parallel:
    - put: app-version
      params:
        bump: major

# endregion

# region firmware

- name: firmware
  serial: true
  serial_groups: [firmware-version]
  plan:
  - <<: *slack_alert
    do:
    - in_parallel:
      - get: firmware-source
        trigger: true
      - put: firmware-version
        params:
          pre: build
      - get: ci
    - task: build
      file: ci/ci/tasks/build_firmware.yml

    - in_parallel:
      - put: firmware-beta-artifact
        params:
          file: artifact/battery_alarm_firmware_mobile.ino.bin.z

      - put: firmware-beta-artifact-version
        params:
          file: firmware-version/version

      - put: firmware-source
        params:
          repository: firmware-source
          tag: firmware-version/version
          tag_prefix: firmware-v
          only_tag: true

- name: release-firmware
  plan:
  - <<: *slack_alert
    do:
    - in_parallel:
      - get: firmware-beta-artifact
        passed: [firmware]
      - get: firmware-version
        passed: [firmware]

    - in_parallel:
      - put: firmware-artifact
        params:
          file: firmware-beta-artifact/firmware-beta.bin
      - put: firmware-artifact-version
        params:
          file: firmware-version/version

- name: bump-firmware-version-patch
  serial_groups: [firmware-version]
  serial: true
  plan:
  - in_parallel:
    - get: firmware-artifact
      passed: [release-firmware]
      trigger: true
    - put: firmware-version
      params:
        bump: patch

- name: bump-firmware-version-minor
  serial_groups: [firmware-version]
  serial: true
  plan:
  - in_parallel:
    - get: firmware-artifact
      passed: [release-firmware]
    - put: firmware-version
      params:
        bump: minor

- name: bump-firmware-version-major
  serial_groups: [firmware-version]
  serial: true
  plan:
  - in_parallel:
    - get: firmware-artifact
      passed: [release-firmware]
    - put: firmware-version
      params:
        bump: major

# endregion

groups:
- name: dev
  jobs:
  - pipeline
  - docs
  - chart
  - deploy
  - app
  - promote-android-internal-to-open
  - promote-android-open-to-prod
  - firmware
  - release-firmware

- name: bump
  jobs:
  - bump-app-version-patch
  - bump-app-version-minor
  - bump-app-version-major
  - bump-firmware-version-patch
  - bump-firmware-version-minor
  - bump-firmware-version-major
